language: go

go:
  - stable
  - 1.14.x
  - 1.13.x

install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -v -test.bench=".*" .

after_success:
  - bash <(curl -s https://codecov.io/bash)